### ISSUE TITLE
Exception when decoding array of zeros

### ISSUE THREAD

**Issue by puuuuh** [ssg/SimpleBase#21]
SimpleBase v2.1.0 works fine, but with SimpleBase v3.0.0+ i got exception

`static void Main(string[] args)
        {
            SimpleBase.Base58.Bitcoin.Decode("11111111111111111111111111");
        }
`

```
Unhandled exception. System.InvalidOperationException: Output buffer was too small while decoding Base58
   at SimpleBase.Base58.Decode(ReadOnlySpan`1 text)
   at TestAddress.Program.Main(String[] args) in /home/puh/RiderProjects/TestAddress/TestAddress/Program.cs:line 9
```

**Comment by ssg** [comment]
This is fixed in 3.0.2.
